"""add alert triggered timestamp

Revision ID: f157a9507491
Revises: 8fd8913bd52a
Create Date: 2026-08-28 17:16:57.191576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f157a9507491'
down_revision: Union[str, Sequence[str], None] = '8fd8913bd52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_alerts', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_alerts', 'triggered_at')
    # ### end Alembic commands ###
